services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: links
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - techno
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - redis_test
  app:
    container_name: myapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    restart: always
    volumes:
      - ./config/config.yml:/app/config/config.yml
      - ./internal/repository/migration:/app/migration
      - ./links.json:/app/links.json
    networks:
      - techno
    environment:
      - APP_MODE=DEV
networks:
  techno:
    driver: bridge
  redis_test:
    driver: bridge

volumes:
  postgres-vol: