services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: links
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/1-init.sql
    networks:
      - techno
  app:
    container_name: myapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./config/.config.yml:/app/config/.config.yml
      - ./internal/repository/migration:/app/migration
    networks:
      - techno
    environment:
      - APP_MODE=DEV
networks:
  techno:
    driver: bridge

volumes:
  postgres-vol: